### ISSUE TITLE
Indentation/Formatting Style

### ISSUE THREAD

**Issue by andrewchawk** [onestruggler/short-intro-reflection#1]
I dislike the current indentation-or-formatting-or-whatever style.

# Suggestions

## Function and Single Argument on Line

I frequently use the following Lispy style:

```
number : Nat
number = _+_ 5
             6
```

The preceding example is obviously a bit contrived and unnecessarily breaks the line but *does* indicate that I try to get some sort of alignment.

## Function on Line

I have also seen some use of the following Lisp style:

```
number : Nat
number = (_+_
           5
           6)
```

## Question and Offer

Do either of these choices appeal to you?  Your current indentation style has confused me at least once.  :-)

In either case, I am willing to fix up the indentation style for you.

**Comment by onestruggler** [comment]
The one with less parenthesis looks good to me. Yes, please help out. Thanks a lot.
________________________________
From: andrewchawk ***@***.***>
Sent: Thursday, August 1, 2024 8:58 PM
To: onestruggler/short-intro-reflection ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [onestruggler/short-intro-reflection] Indentation Style (Issue #1)

CAUTION: The Sender of this email is not from within Dalhousie.

I dislike the current indentation-or-formatting-or-whatever style.

Suggestions
Function and Single Argument on Line

I frequently use the following Lispy style:

number : Nat
number = _+_ 5
             6


The preceding example is obviously a bit contrived and unnecessarily breaks the line but does indicate that I try to get some sort of alignment.

Function on Line

I have also seen some use of the following Lisp style:

number : Nat
number = (_+_
           5
           6)


Question and Offer

Do either of these choices appeal to you? Your current indentation style has confused me at least once. :-)

I am willing to fix up the indentation style for you.

**Comment by andrewchawk** [comment]
Also, do you have a preferred maximum line length?

Also, do you have oppose breaking lines after the equals sign?  An example is as follows:

```
example =
  reallyReallyReallyReallyReallyReallyYouGetItLongDefinition
```

**Comment by andrewchawk** [comment]
Also *still*, are you intentionally avoiding the standard library?

**Comment by onestruggler** [comment]
Yes, I am avoiding it to be self-contained.
________________________________

**Comment by onestruggler** [comment]
Long line is indeed not looking good. I don't want to break it without a cause, I am thinking to break the long ones by assumptions and the conclusion. But not for short ones. E.g

Lemma1 : Nat -> Nat -> Nat -> Nat

===>

Lemma1 :
      Nat ->
      Nat ->
      Nat ->
      Nat

Similarly in the definition of Lemma1.

For comments, emacs' agda-mode has a default line width (probably around 80 characters), I just press Alt+q to auto-wrap my comments. It's not working for code.


________________________________
