### ISSUE TITLE
Odd Wording

### ISSUE THREAD

**Issue by andrewchawk** [onestruggler/short-intro-reflection#2]
My question pertains to the following segment:

```
-- let [_] = unquote ∘ myast-of ∘ quoteTerm, we see by varing the
-- equation in check1, and by thinking of unquote as the inverse of
-- quoteTerm (only true in TC) that:
```

Is "varing" a typo of "varying"?  I am not too certain about any possibilities here.

**Comment by onestruggler** [comment]
Sorry for my bad phrasing. It should be varying. But what I mean is just to apply unquote to both sides of check1.

You probably have a better way to say it, please improve it. Thanks.
________________________________
From: andrewchawk ***@***.***>
Sent: Monday, August 5, 2024 10:52 PM
To: onestruggler/short-intro-reflection ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [onestruggler/short-intro-reflection] Odd Wording (Issue #2)

CAUTION: The Sender of this email is not from within Dalhousie.

My question pertains to the following segment:

-- let [_] = unquote ∘ myast-of ∘ quoteTerm, we see by varing the
-- equation in check1, and by thinking of unquote as the inverse of
-- quoteTerm (only true in TC) that:


Is "varing" a typo of "varying"? I am not too certain about any possibilities here.
