### ISSUE TITLE
Literate Agda

### ISSUE THREAD

**Issue by andrewchawk** [onestruggler/short-intro-reflection#3]
Are you at all interested in having the main file converted to a LaTeX-based literate Agda file?  The main advantages are good markup and even better presentation.

**Comment by onestruggler** [comment]
yes, very much, but I don't have time for that for now. Literate agda would be a great improvement.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: andrewchawk ***@***.***>
Sent: Thursday, August 8, 2024 11:48:42 PM
To: onestruggler/short-intro-reflection ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [onestruggler/short-intro-reflection] Literate Agda (Issue #3)

CAUTION: The Sender of this email is not from within Dalhousie.

Are you at all interested in having this project converted to a LaTeX-based literate Agda file? The main advantages are good markup and even better presentation.

**Comment by andrewchawk** [comment]
> yes, very much, but I don't have time for that for now. Literate agda would be a great improvement.

I might go ahead and make the necessary changes.

**Comment by onestruggler** [comment]
Yes, please. Thanks a lot.
________________________________

**Comment by andrewchawk** [comment]
Do you want Unicode arrows, too?  I think that the ASCII arrows look kind of nasty in a compiled PDF.

**Comment by onestruggler** [comment]
yes, of course. I was just being lazy.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by andrewchawk** [comment]
The change began with f304c49b6f00c5ba46b521cc522ce576f9d34e57.  Closing all of these issues with a single pull request will either be great or really, really unpleasant for you.  :-)

**Comment by onestruggler** [comment]
it's great for me. thanks a lot.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
